version: "3.7"

services:
  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong-net
    environment:
      # Let Konga use local db
      # DB_ADAPTER: postgres
      # DB_DATABASE: konga_db
      # DB_HOST: kong-database
      # DB_USER: kong
      TOKEN_SECRET: Sup3rS3cret!123
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"