apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ext-bin
spec:
  rules:
  - host: ext-bin.com
    http:
      paths:
      - backend:
          serviceName: ext-httpbin
          servicePort: 80