apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ext-bin
  annotations:
    konghq.com/plugins: viz-rate-limit
spec:
  rules:
  - http:
      paths:
      - path: /get
        backend:
          serviceName: httpbin
          servicePort: 80